/* eslint-disable @typescript-eslint/naming-convention */

import { IconName } from "../types/icon";
import { HecEyeIcons } from "./HecEyeIcons";

export const MarkerSymbols: { [key: string]: IconName } = {
  aed: HecEyeIcons.AED_ICON,
  airport: HecEyeIcons.AIRPORT_ICON,
  "amusement-park": HecEyeIcons.AMUSEMENT_PARK_ICON,
  aquarium: HecEyeIcons.AQUARIUM_ICON,
  bicycle: HecEyeIcons.BICYCLE_ICON,
  blocked: HecEyeIcons.BLOCKED_ICON,
  building: HecEyeIcons.BUILDING_ICON,
  bus: HecEyeIcons.BUS_ICON,
  "bus-stop": HecEyeIcons.BUS_STOP_ICON,
  camp: HecEyeIcons.CAMP_ICON,
  car: HecEyeIcons.CAR_ICON,
  cattle: HecEyeIcons.CATTLE_ICON,
  caution: HecEyeIcons.CAUTION_ICON,
  collapse: HecEyeIcons.COLLAPSE_ICON,
  confirmation: HecEyeIcons.CONFIRMATION_ICON,
  construction: HecEyeIcons.CONSTRUCTION_ICON,
  damaged: HecEyeIcons.DAMAGED_ICON,
  "evacuation-area": HecEyeIcons.EVACUATION_AREA_ICON,
  farm: HecEyeIcons.FARM_ICON,
  ferry: HecEyeIcons.FERRY_ICON,
  fire: HecEyeIcons.FIRE_ICON,
  "fire-brigade-station": HecEyeIcons.FIRE_BRIGADE_STATION_ICON,
  "fire-cistern": HecEyeIcons.FIRE_CISTERN_ICON,
  "fire-extinguisher": HecEyeIcons.FIRE_EXTINGUISHER_ICON,
  "fire-hydrant": HecEyeIcons.FIRE_HYDRANT_ICON,
  flag: "flag checkered",
  flood: HecEyeIcons.FLOOD_ICON,
  "gas-cutoff": HecEyeIcons.GAS_CUTOFF_ICON,
  "gas-station": HecEyeIcons.GAS_STATION_ICON,
  heritage: HecEyeIcons.HERITAGE_ICON,
  hospital: HecEyeIcons.HOSPITAL_ICON,
  hotel: HecEyeIcons.HOTEL_ICON,
  information: HecEyeIcons.INFORMATION_ICON,
  landslide: HecEyeIcons.LANDSLIDE_ICON,
  leakage: HecEyeIcons.LEAKAGE_ICON,
  missing: HecEyeIcons.MISSING_ICON,
  museum: HecEyeIcons.MUSEUM_ICON,
  "natural-water": HecEyeIcons.NATURAL_WATER_ICON,
  park: HecEyeIcons.PARK_ICON,
  parking: HecEyeIcons.PARKING_ICON,
  police: HecEyeIcons.POLICE_ICON,
  "post-office": HecEyeIcons.POST_OFFICE_ICON,
  restaurant: HecEyeIcons.RESTAURANT_ICON,
  "retirement-home": HecEyeIcons.RETIREMENT_HOME_ICON,
  rice: HecEyeIcons.RICE_ICON,
  school: HecEyeIcons.SCHOOL_ICON,
  shelter: HecEyeIcons.SHELTER_ICON,
  shopping: HecEyeIcons.SHOPPING_ICON,
  shrine: HecEyeIcons.SHRINE_ICON,
  sign: "map signs",
  "smoking-area": HecEyeIcons.SMOKING_AREA_ICON,
  spa: HecEyeIcons.SPA_ICON,
  star: "star",
  station: HecEyeIcons.STATION_ICON,
  taxi: HecEyeIcons.TAXI_ICON,
  temple: HecEyeIcons.TEMPLE_ICON,
  thumbtack: "thumbtack",
  toilet: HecEyeIcons.TOILET_ICON,
  "traffic-accident": HecEyeIcons.TRAFFIC_ACCIDENT_ICON,
  "vacant-house": HecEyeIcons.VACANT_HOUSE_ICON,
  "water-cutoff": HecEyeIcons.WATER_CUTOFF_ICON,
  wifi: HecEyeIcons.WIFI_ICON,
  zoo: HecEyeIcons.ZOO_ICON,
} as const;
